#!/usr/bin/env bash
#
# run as ubuntu

set -o errexit
set -o xtrace

if [[ `whoami` != 'ubuntu' ]]; then
    echo "This script must be run as ubuntu."
    exit 1
fi

_HERE=$(cd $(dirname "$0"); pwd)
SRC_DIR="${_HERE}"
TARGET_DIR="/home/bluesky"
DATE=$(date +%Y%m%dT%H%M)

# save 1 level of backups
sudo mkdir -p "${TARGET_DIR}"
sudo chmod -f 755 "${TARGET_DIR}"
sudo rm -rfd "${TARGET_DIR}/"backup.*
sudo mkdir "${TARGET_DIR}/backup.${DATE}"

# copy over current data
sudo cp -r "${SRC_DIR}" "${TARGET_DIR}"

# get pool for s3 configs
mypool="$(grep ec2.pool /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
mycluster="$(grep ec2.cluster /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"

# copy over important configs
pds_hostname="$(grep bluesky.hostname /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_jwt_secret="$(grep bluesky.jwt_secret /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_admin_password="$(grep bluesky.admin_password /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_plc_rotation="$(grep bluesky.plc_rotation /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_data_directory="$(grep bluesky.data_directory /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_blobstore_disk_location="$(grep bluesky.blobstore_disk_location /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_blob_upload_limit="$(grep bluesky.blob_upload_limit /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_did_plc_url="$(grep bluesky.did_plc_url /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_app_view_url="$(grep bluesky.app_view_url /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_app_view_did="$(grep bluesky.app_view_did /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_report_service_url="$(grep bluesky.report_service_url /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_report_service_did="$(grep bluesky.report_service_did /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_crawlers="$(grep bluesky.crawlers /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_log_enabled="$(grep bluesky.log_enabled /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_email_smtp_url="$(grep bluesky.email_smtp_url /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"
pds_email_from_address="$(grep bluesky.email_from_address /ebsa/config/services.config | cut -d '=' -f 2 | head -1)"

echo "# generated by internal build script on $(date)" > /tmp/env.production
echo "#" >> /tmp/env.production
echo "PDS_HOSTNAME=${pds_hostname}" >> /tmp/env.production
echo "PDS_JWT_SECRET=${pds_jwt_secret}" >> /tmp/env.production
echo "PDS_ADMIN_PASSWORD=${pds_admin_password}" >> /tmp/env.production
echo "PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=${pds_plc_rotation}" >> /tmp/env.production
echo "PDS_DATA_DIRECTORY=${pds_data_directory}" >> /tmp/env.production
echo "PDS_BLOBSTORE_DISK_LOCATION=${pds_blobstore_disk_location}" >> /tmp/env.production
echo "PDS_BLOB_UPLOAD_LIMIT=${pds_blob_upload_limit}" >> /tmp/env.production
echo "PDS_DID_PLC_URL=${pds_did_plc_url}" >> /tmp/env.production
echo "PDS_BSKY_APP_VIEW_URL=${pds_app_view_url}" >> /tmp/env.production
echo "PDS_BSKY_APP_VIEW_DID=${pds_app_view_did}" >> /tmp/env.production
echo "PDS_REPORT_SERVICE_URL=${pds_report_service_url}" >> /tmp/env.production
echo "PDS_REPORT_SERVICE_DID=${pds_report_service_did}" >> /tmp/env.production
echo "PDS_CRAWLERS=${pds_crawlers}" >> /tmp/env.production
echo "LOG_ENABLED=${pds_log_enabled}" >> /tmp/env.production
echo "PDS_EMAIL_SMTP_URL=${pds_email_smtp_url}" >> /tmp/env.production
echo "PDS_EMAIL_FROM_ADDRESS=${pds_email_from_address}" >> /tmp/env.production

sudo mv "/tmp/env.production" "${TARGET_DIR}/pds.env"

# get correct user
sudo chown -R ubuntu:ubuntu /home/bluesky

# get packages
cd /ebsa/bluesky/current/service
npm install --production --frozen-lockfile

exit 0
